export default {
  pl: {
    yes: 'Tak',
    no: 'Nie',
    is: 'Jest',
    none: 'Brak',
    save: 'Zapisz',
    cancel: 'Anuluj',
    loading: 'Ładowanie',
    search: 'Szukaj',
    backToResults: 'Powrót do wyników',
    locationInfo: {
      address: 'Adres',
      operator: 'Operator',
      phone: 'Telefon',
      openingHours: 'Godziny otwarcia',
      prepareInstruction: 'Instrukcje przygotowawcze',
      lastUpdate: 'Ostatnia aktualizacja',
    },
    locationType: {
      transport: 'Transport',
      hospital: 'Szpital',
    },
    noResults: 'Nic nie znaleziono',
    connectionProblem: {
      map: 'Nie można nawiązać połączenia z bazą lokacji.',
      location: 'Nie udało się pobrać danych lokacji.',
      logs: 'Nie udało się połączyć z bazą logów :(',
    },
    markerForm: {
      heading: {
        addMarker: 'Dodaj nowe miejsce',
        editMarker: 'Edytuj miejsce',
      },
      assignedUserId: 'ID przypisanego użytkownika',
      location: 'Położenie geograficzne',
      locationHint: 'Postaraj się jak najdokładniej umieścić pinezkę lokacji na mapie. Podczas dodawania nowej lokacji możesz przesuwać pinezkę, aby wyznaczyć lokalizację jak najdokładniej. Możesz też wpisać współrzędne w odpowiednie pole, wtedy pinezka przeniesie się w podane miejsce.',
      place: 'Nazwa miejsca',
      placeHint: 'Postaraj się aby nazwa lokacji była krótka i unikatowa, związana z konkretnym miejscem które dodajesz, tak aby potem można je było łatwo znaleźć. Jeśli lokacja nie ma nazwy własnej (np. Schron Czumak) to warto nawiązać do charakterystycznych punktów znajdujących się w pobliżu. Staraj się unikać ogólnych nazw, takich jak „Wiata przy jeziorze”. Zamiast tego możesz napisać „Wiata przy jeziorze Bukowskim” albo „Chatka przy zielonym szlaku na Turbacz” co ułatwi przeglądanie i wyszukiwanie.',
      type: 'Typ miejsca',
      typeHint: 'Wybierz odpowiedni typ miejsca. Dzięki temu na mapie pokaże się odpowiednia ikona i osoby zainteresowane, na przykład tylko wieżami widokowymi, będą mogły łatwo znaleźć Twoje miejsce.',
      description: 'Opis miejsca',
      descriptionHint: 'W opisie podaj przydatne dla odwiedzających informacje, takie jak wielkość, liczbę miejsc, dostępność, ochrona przed deszczem, jakie są zasady korzystania, dane właściciela i inne adekwatne do dodawanej lokacji. W opisie nie podawaj: współrzędnych lokacji (jest na nie osobne pole), wskazówek dojścia na miejsce (również jest na to osobne pole), informacji o dostępności wody i ognia (są na to osobne pola na końcu formularza).',
      directionsHint: 'W polu wskazówki dojścia wpisz szczegóły gdzie leży dane miejsce i jak do niego dotrzeć, np. chatkowym szlakiem od odejścia zielonego, w kępie krzaków na łące, mostkiem od północy itp. Pomyśl, że jesteś już blisko, ale jest środek nocy i nic nie widać i ta informacja ma Cię doprowadzić do celu.',
      waterDescription: 'Opis dostępu do wody (opcjonalnie)',
      waterDescriptionHint: 'Podaj szczegóły, np. jak wydajny jest strumień.',
      fireDescription: 'Opis dostępu do ognia (opcjonalnie)',
      fireDescriptionHint: 'Podaj szczegóły, np. skąd wziąć drewno.',
    },
    notifications: {
      markerUpdated: 'Marker zaktualizowany.',
      newMarkerAdded: 'Dodano nowy marker.',
      couldNotSaveMarker: 'Nie udało się zapisać markera.',
      photoAdded: 'Dodano nowe zdjęcie.',
      couldNotSavePhoto: 'Nie udało się zapisać zdjęcia.',
      wrongCoordsFormat: 'Niepoprawny format współrzędnych.',
      couldNotRestoreSession: 'Nie udało się uwierzytelnić. Spróbuj się wylogować i zalogować ponownie.',
    },
    actions: {
      edit: 'Edytuj',
      addPhoto: 'Dodaj zdjęcie',
    },
    addMarkerHere: 'Dodaj tu lokację',
    auth: {
      loginSuccessful: 'Zalogowano pomyślnie',
      login: 'Logowanie',
      logout: 'Wyloguj',
    },
    language: 'Język',
    selectLanguage: 'Wybierz nowy język',
    languageChanged: 'Język zmieniony.',
    administration: 'Administracja',
    informations: 'Informacje',
    termsAndConditions: 'Regulamin',
    privacyPolicy: 'Polityka prywatności',
    goToMyLocation: 'Pokaż mój punkt',
    pleaseEnableGeolocation: 'Potrzebujemy lokacji twojego urządzenia, aby wyświetlić najblisze punkty w Twojej okolicy.',
    welcomeText: 'Witaj w aplikacji, która pomoże ci znaleźć najbliższe miejsce, do którego należy zgłosić się, aby otrzymać pomoc w przypadku zauważenia u siebie symptomów COVID-19.',
    mainName: 'Dokąd z wirusem',
    waitingTime: 'Czas oczekiwania',
    waitingTimes: {
      short: 'Natychmiast',
      moderate: 'Umiarkowany',
      long: 'Długi',
    },
  },


  en: {
    yes: 'Yes',
    no: 'No',
    is: 'Is available',
    none: 'None',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading',
    search: 'Search',
    backToResults: 'Back to results',
    locationInfo: {
      address: 'Address',
      operator: 'Operator',
      phone: 'Phone',
      openingHours: 'Opening hours',
      prepareInstruction: 'Prepare instruction',
      lastUpdate: 'Last update',
    },
    locationType: {
      transport: 'Transport',
      hospital: 'Hospital',
    },
    noResults: 'No results',
    connectionProblem: {
      map: 'Could not connect to the database of locations.',
      location: 'Could not load the location details.',
      logs: 'Could not connect to the database of locations.',
    },
    markerForm: {
      heading: {
        addMarker: 'Add new place',
        editMarker: 'Edit place',
      },
      assignedUserId: 'Assigned user ID',
      location: 'Coordinates',
      locationHint: 'English hints.',
      place: 'Name of the place',
      placeHint: 'English hints.',
      type: 'Type of the place',
      typeHint: 'English hints.',
      description: 'Description',
      descriptionHint: 'English hints.',
      directionsHint: 'English hints.',
      waterDescription: 'Access to water description (optional)',
      waterDescriptionHint: 'English hints.',
      fireDescription: 'Access to fire description (optional)',
      fireDescriptionHint: 'English hints.',
    },
    notifications: {
      markerUpdated: 'Marker updated.',
      newMarkerAdded: 'New marker added.',
      couldNotSaveMarker: 'Could not save a marker.',
      photoAdded: 'Photo added.',
      couldNotSavePhoto: 'Could not save a photo.',
      wrongCoordsFormat: 'Wrong coordinations format.',
      couldNotRestoreSession: 'Could not authenticate. Try to log out and log in again.',
    },
    actions: {
      edit: 'Edit',
      addPhoto: 'Add photo',
    },
    addMarkerHere: 'Add location here',
    auth: {
      loginSuccessful: 'Login successful',
      login: 'Login',
      logout: 'Logout',
    },
    language: 'Language',
    administration: 'Administration',
    selectLanguage: 'Select language',
    languageChanged: 'Language changed.',
    informations: 'Informations',
    termsAndConditions: 'Terms and conditions',
    privacyPolicy: 'Privacy policy',
    goToMyLocation: 'Go to my location',
    pleaseEnableGeolocation: 'We need a location of your device to show the neares points in your area.',
    welcomeText: 'Welcome in the app, that will help you to find the nearest place to go, to get help in case of noticing any COVID-19 symptoms.',
    mainName: 'Where to go with the virus',
    waitingTime: 'Waiting time',
    waitingTimes: {
      short: 'Immediately',
      moderate: 'Moderate',
      long: 'Long',
    },
  },
}
